openapi: 3.0.3
info:
  title: API-MS-CADASTRO-FILIAL
  description: |
    Realiza o Cadstro de Filiais
  contact: {}
  version: 1.0.0
servers:
  - url: https://localhost:8080/api/v1/
tags:
  - name: Filiais
paths:
  /filiais:
    post:
      tags:
        - Filiais
      summary: "Criar o Cadastro da Filial"
      description: Método para realizar o cadastro da Filial
      operationId: create
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrateFilialRequest'
        required: true
      responses:
        201:
          description: Created
        401:
          description: Cabeçalho de autenticação ausente/inválido ou token inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

        403:
          description: O token tem escopo incorreto ou uma política de segurança foi
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        405:
          description: Method Not Allowed
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        415:
          description: Unsupported Media Type
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        422:
          description: A requisição foi malformada, omitindo atributos obrigatórios,
            seja no payload ou através de atributos na URL.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

        500:
          description: Ocorreu um erro no gateway da API ou no microsserviço
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        503:
          description: Servidor temporariamente indisponível
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
  /filiais/{id}:
    get:
      tags:
        - Filiais
      summary: "Obter Filial Por ID"
      description: Método para realizar o cadastro da Postagem
      operationId: getById
      parameters:
        - name: id
          in: path
          description: ID da Filial
          required: true
          schema:
            type: string
      responses:
        200:
          description: Obtem todas as Postagens
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFilialResponse'

        401:
          description: Cabeçalho de autenticação ausente/inválido ou token inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

        403:
          description: O token tem escopo incorreto ou uma política de segurança foi
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        405:
          description: Method Not Allowed
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        415:
          description: Unsupported Media Type
            violada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        422:
          description: A requisição foi malformada, omitindo atributos obrigatórios,
            seja no payload ou através de atributos na URL.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'

        500:
          description: Ocorreu um erro no gateway da API ou no microsserviço
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'
        503:
          description: Servidor temporariamente indisponível
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseError'



components:
  schemas:
    CrateFilialRequest:
      required:
        - nome
        - cnpj
        - matricula-gestor
      type: object
      properties:
        nome:
          maxLength: 255
          type: string
          nullable: true
          example: 'Loja Maia Centro'
        cnpj:
          maxLength: 20
          nullable: true
          type: string
          example: '02308611000127'
        matricula-gestor:
          maxLength: 50
          nullable: true
          type: string
          example: '10121'

    GetFilialResponse:
      type: object
      properties:
        id:
          type: string
          example: 'a5ef3310-a0a1-11ed-a8fc-0242ac120002'
        nome:
          maxLength: 255
          type: string
          example: 'Loja Maia Centro'
        cnpj:
          maxLength: 255
          type: string
          example: '02308611000127'
        gestor:
          $ref: '#/components/schemas/GestorFilialResponse'
        data-criacao:
          type: string
          format: date-time
          example: '2023-01-20'
        data-update:
          type: string
          format: date-time
          example: '2023-01-20'

    GestorFilialResponse:
      type: object
      properties:
        matricula:
          type: string
          example: 'BC-20200'
        nome:
          maxLength: 255
          type: string
          example: 'Loja Maia Centro'
        cpf:
          maxLength: 255
          type: string
          example: '02308611000127'
        email:
          maxLength: 255
          type: string
          example: 'employee@email.com'


    ResponseError:
      title: ResponseError
      type: object
      properties:
        correlationId:
          maxLength: 255
          type: string
          description: Código de identificação da request
        error:
          $ref: '#/components/schemas/Error'

    Error:
      title: Error
      type: object
      properties:
        code:
          maxLength: 255
          type: string
          description: Código de erro específico do endpoint
        type:
          maxLength: 255
          type: string
          description: Título legível por humanos deste erro específico
        message:
          maxLength: 2048
          type: string
          description: Descrição legível por humanos deste erro específico
